import re


def regexGenerator(word, A, B):
    """
    Creates a regex expression for a given word and two sets of characters.

    Args:
        word (String): A word entered by the user
        A (Set): The characters available in the keyboard
        B (Set): The characters not available in the keyboard
    """
    regex = ""
    diff = A - B
    for c in word:
        if c in A:
            regex += c
        elif c == "_":
            regex += "."

        else:
            print(c in A)
            regex += f'{diff}'
    return regex


def findWords(word, A, B):
    """
    Finds words that match the regex expression generated by regexGenerator().

    Args:
        word (String): A word entered by the user
        A (Set): The characters available in the keyboard
        B (Set): The characters not available in the keyboard
    """
    regex = regexGenerator(word, A, B)
    print(regex)
    with open(f"KeyboardOptomisation/Wordlist/{len(word)}_length.txt", 'r') as file:
        words = file.read().split()
    for word in words:
        if re.match(regex, word):
            print(word)


A = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
     'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'x', 'y', 'z'}


findWords("h___o", A, A - {'l', 'o'})
